name: Scrape Kasten Docs

on:
  schedule:
    - cron: "0 3 * * *"  # Todos los días a las 03:00 UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: |
          pip install -r scraper/requirements.txt

      - name: Ejecutar scraper
        run: python scraper/scraper.py

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Actualización automática de documentación [$(date)]" || echo "Sin cambios"
          git push
